name: dwichs-back
services:
  dwichs-database:
    image: postgres
    container_name: dwichs-database
    hostname: dwichs-database
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: dwichs
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    networks:
      - dwichs
    volumes:
      - dwichs-database:/var/lib/postgresql/data

  dwichs-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: dwichs-api
    hostname: dwichs-api
    restart: unless-stopped
    command: npm run dev
    ports:
      - 3000:3000
    networks:
      - dwichs
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src

        - action: sync
          path: ./prisma
          target: /app/prisma

        - action: rebuild
          path: package.json
          target: /app

        - action: rebuild
          path: .env
          target: /app

  dwichs-prisma-studio:
    image: node:22
    container_name: dwichs-prisma-studio
    ports:
      - 5555:5555
    restart: unless-stopped
    working_dir: /app
    command: npx prisma studio --schema=/app/prisma/schema.prisma
    networks:
      - dwichs
    volumes:
      - ./:/app # Ensures your project files including prisma/ are available

volumes:
  dwichs-database:
    name: "dwichs-database"

networks:
  dwichs:
