name: dwichs-back
services:
  dwichs-database:
    image: postgres
    container_name: dwichs-database
    hostname: dwichs-database
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: dwichs
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - dwichs-database:/var/lib/postgresql/data

  dwichs-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: dwichs-api
    hostname: dwichs-api
    restart: unless-stopped
    command: npm run dev
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src

        - action: sync
          path: ./prisma
          target: /app/prisma

        - action: rebuild
          path: package.json
          target: /app

  # dwichs-adminer:
  #   image: adminer
  #   container_name: dwichs-adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #
  # dwichs-pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: dwichs-pgadmin
  #   ports:
  #     - 80:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=karichikarichikarichi@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   volumes:
  #     - ~/docker/container/pgadmin:/var/lib/pgadmin

volumes:
  dwichs-database:
    name: "dwichs-database"
