services:
  database.dev:
    image: postgres
    container_name: dwichs-database.dev
    hostname: dwichs-database.dev
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: dwichs
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    networks:
      - dwichs.dev
    volumes:
      - dwichs-database.dev:/var/lib/postgresql/data

  api.dev:
    build:
      context: .
      dockerfile: Dockerfile.api
      target: dev
      tags:
        - dwichs-api.dev
    container_name: dwichs-api.dev
    hostname: dwichs-api.dev
    restart: unless-stopped
    command: npm run dev
    ports:
      - 3000:3000
    networks:
      - dwichs.dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src

        - action: sync
          path: ./prisma
          target: /app/prisma

        - action: rebuild
          path: package.json
          target: /app

        - action: rebuild
          path: .env
          target: /app

  prisma-studio.dev:
    image: node:22
    container_name: dwichs-prisma-studio.dev
    ports:
      - 5555:5555
    restart: unless-stopped
    working_dir: /app
    command: npx prisma studio --schema=/app/prisma/schema.prisma
    networks:
      - dwichs.dev
    volumes:
      - ./:/app # Ensures your project files including prisma/ are available

volumes:
  dwichs-database.dev:
    name: "dwichs-database.dev"

networks:
  dwichs.dev:
    name: dwichs.dev
