name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  deploy-swarm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Swarm node to known hosts
        run: |
          ssh-keyscan 188.245.46.180 >> ~/.ssh/known_hosts

      - name: Login to GHCR on Swarm node
        run: |
          ssh -i ~/.ssh/id_rsa github-action@188.245.46.180 \
            "docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_GITHUB_TOKEN }}"
        env:
          GHCR_GITHUB_TOKEN: ${{ secrets.GHCR_GITHUB_TOKEN }}

      - name: Create .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "NODE_ENV=production" >> .env

      - name: Deploy to Docker Swarm
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: github-action@188.245.46.180
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }} # known_hosts entry
          deployment_mode: docker-swarm
          stack_file_name: docker-compose.production.yml
          keep_files: 5
          args: dwichs # your stack name
