name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  deploy-swarm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 188.245.46.180 >> ~/.ssh/known_hosts

      - name: Login to GHCR on Swarm node
        run: |
          ssh -i ~/.ssh/id_rsa github-action@188.245.46.180 \
            "docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_GITHUB_TOKEN }}"
        env:
          GHCR_GITHUB_TOKEN: ${{ secrets.GHCR_GITHUB_TOKEN }}

      - name: Get the code from github
        uses: actions/checkout@v4

      - name: Deploy to Docker Swarm
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "NODE_ENV=production" >> .env
          pwd
          ls -al
          docker context create dwichs-hetzner --docker "host=ssh://github-action@188.245.46.180"
          docker context use dwichs-hetzner
          docker stack deploy -c docker-compose.production.yml dwichs --with-registry-auth
